FROM eclipse-temurin:17-jdk-alpine

WORKDIR /app

COPY target/*.jar /app/app.jar

EXPOSE 9090

ENTRYPOINT ["java","-XX:+UseContainerSupport","-XX:MaxRAMPercentage=75","-Dserver.port=9090","-Dserver.address=0.0.0.0","-jar","/app/app.jar"]
