env=${ENV}
server.servlet.context-path=/api/v2
spring.config.import=optional:file:.env[.properties]

# /api-docs endpoint custom path
springdoc.api-docs.path=/api-docs
spring.main.allow-circular-references=true

spring.data.mongodb.uri=mongodb+srv://${MONGODB_USERNAME}:${MONGODB_PASSWORD}@${MONGODB_CLUSTER}/${MONGODB_DATABASE}

app.domain=${APP_DOMAIN}

app.secret.key=${APP_SECRET_KEY}


#PetPooja Properties
pos.petpooja.url=${POS_PETPOOJA_URL}
pos.petpooja.token=${POS_PETPOOJA_TOKEN}
pos.petpooja.secret=${POS_PETPOOJA_SECRET}
pos.petpooja.key=${POS_PETPOOJA_KEY}

#RazorPay Properties
razorpay.key = ${RAZORPAY_KEY}
razorpay.secret = ${RAZORPAY_SECRET}

#SMS 
sms.url=https://2factor.in/API/V1/{key}/SMS/{mobile}/{otp}
sms.key=${SMS_KEY}

#Pidge Properties
delivery.pidge.url=${DELIVERY_PIDGE_URL}
delivery.pidge.username=${DELIVERY_PIDGE_USERNAME}
delivery.pidge.password=${DELIVERY_PIDGE_PASSWORD}
delivery.pidge.token=${DELIVERY_PIDGE_TOKEN}
delivery.pidge.smart.id=${DELIVERY_PIDGE_SMARTID}
google.api.key=${GOOGLE_KEY}

logging.level.com.hyp.config.LoggingFilterConfig=DEBUG
cors.allowed.origins=${CORS_ALLOWED_ORIGINS}
cors.server-ips=178.16.137.243,157.173.219.155,82.29.161.43


notification.meta.url=https://graph.facebook.com/v20.0
notification.meta.app=3479548262291960
notification.meta.token=${NOTIFICATION_META_TOKEN}
notification.meta.phone=112915418570784
notification.meta.acct=121878920999700
management.endpoints.web.exposure.include=*

notification.email.address=hyperapps@googlegroups.com
internal.users.numbers=9965861660

#logging.level.org.springframework.web.socket=DEBUG
#logging.level.org.springframework.messaging=DEBUG
#logging.level.net.bull.javamelody=DEBUG

# JavaMailSender properties
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=hyperappschennai@gmail.com
spring.mail.password=${MAIL_APP_PASSWORD}
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000


# Additional configurations
spring.mail.default-encoding=UTF-8
spring.mail.test-connection=false

#Back blaze bucket 
bucket.id=1f0c72d17d83
bucket.name=hyp-bucket
bucket.key=${BUCKET_KEY}
bucket.url=https://f005.backblazeb2.com/file

#Redis cache
spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=${REDIS_PORT}
spring.data.redis.password=${REDIS_PASSWORD}

#OneSignal 
onesignal.api.url=https://api.onesignal.com
onesignal.api.key=${ONE_SIGNAL_KEY}
onesignal.partner.api.key=os_v2_app_bmuzuqcewffhjbqygzttj6cdyierw275hyeufc5t7qnsiobw27lwhg7g5rpfu5tevhcpl63zs7rjm7cj4ih2nb2tn67o7kcc6ky5u5i
onesignal.app.id=907a194a-f661-47b3-9199-bdafd091440d
onesignal.partner.app.id=0b299a40-44b1-4a74-8618-366734f843c2

#javamelody.init-parameters.log=true
#javamelody.monitoring-path=/monitoring
#javamelody.spring-monitoring-enabled=false
#javamelody.url-exclude-pattern: (/webjars/.*|/css/.*|/images/.*|/fonts/.*|/js/.*) 
#http-transform-pattern: \d+
#authorized-users: admin:pwd

#os_v2_app_njrm2ewhebabvga3rdhfi7mkml7glxpbkboejjv47quomrbgkcqht65rlcvbseuccbr5cgtxxeyiihxo76liwbyqi3szmch3kmklxdq

#os_v2_app_r7kbs446uvg47n36qv6dwzo72vnqz74giyxedy4ukop6w7tfciwuje2qgjggwy5uv5yt5nxnwfi3rahqrmoiovrlz6msaoft42j44hi

temporal.server.host=${TEMPORAL_HOST}
temporal.server.port=${TEMPORAL_PORT}
