#WyrMq0goUbpIEyHb 
#mongodbuser

spring.data.mongodb.uri=mongodb+srv://mongodbuser:WyrMq0goUbpIEyHb@cluster-0.wqam8zz.mongodb.net/hyp_backend_mdb

myapp.domain=https://aardvark-notable-terminally.ngrok-free.app

#PetPooja Properties
pos.petpooja.url=https://47pfzh5sf2.execute-api.ap-southeast-1.amazonaws.com/V1
pos.petpooja.token=1306d6f5f3332a3e3a35c77909f8cdf77831cef3
pos.petpooja.secret=154e9636cfb4a98a00933f6aeffbbd92c814e482
pos.petpooja.key=13yrzmb9pivxscoh25gdj0t7fk48uaqw

#RazorPay Properties
razorpay.key = rzp_test_dUt1jZJm3Whtxk
razorpay.secret = 6vkVGOpiJUZdBvbSQxpqK82Z

sms.url=https://2factor.in/API/V1/{key}/SMS/{mobile}/{otp}
sms.key=e852dcd1-b3c7-11eb-8089-0200cd936042