package com.hyp.enums;

public enum DeliveryFulfillStatusType {
	CREATED, CANCELLED, OUT_FOR_PICKUP, REACHED_PICKUP, PICKED_UP, IN_TRANSIT, OUT_FOR_DELIVERY, REACHED_DELIVERY,
	DELIVERED, UNDELIVERED, RTO_OUT_FOR_DELIVERY, RTO_UNDELIVERED, RTO_DELIVERED, LOST, DAMAGED;
}
